/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.UserBUS;
import com.example.sdksamples.ReadTags;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class LoginForm extends javax.swing.JFrame {
    public UserBUS userBUS = new UserBUS();

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jBtnLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTxtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, 30));

        jBtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnLogin.setText("ĐĂNG NHẬP");
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("USERNAME");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 80, 30));

        jTxtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtUsernameKeyPressed(evt);
            }
        });
        jPanel1.add(jTxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHẦN MỀM NHẬP XUẤT KHO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 250, 40));

        jTxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jTxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 72, 320, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
        // TODO add your handling code here:
        if (jTxtUsername.getText().equals("") || jTxtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Username and password cannot be left blank!");
            return;
        }
        Dashboard.userLogin = userBUS.checkLogin(jTxtUsername.getText(), jTxtPassword.getText());
        if (Dashboard.userLogin != null) {
            if (Dashboard.userLogin.getRole() < 0) {
                JOptionPane.showMessageDialog(this, "Login fail! User was blocked.");
                Dashboard.userLogin = null;
                return;
            }
            if (Dashboard.userLogin.getRole() == 0) {
                JOptionPane.showMessageDialog(this, "Login fail! User was removed.");
                Dashboard.userLogin = null;
                return;
            }
            JOptionPane.showMessageDialog(this, "Login success!");
            this.setVisible(false);
            ReadTags.visibleDashboard();
//            ReadTags rt = new ReadTags();
//            rt.main();
        } else {
            JOptionPane.showMessageDialog(this, "Login fail! Username or password incorrect.");
        }
    }//GEN-LAST:event_jBtnLoginActionPerformed

    private void jTxtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUsernameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtnLogin.doClick();
        }
    }//GEN-LAST:event_jTxtUsernameKeyPressed

    private void jTxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBtnLogin.doClick();
        }
    }//GEN-LAST:event_jTxtPasswordKeyPressed

    public JPasswordField getjTxtPassword() {
        return jTxtPassword;
    }

    public void setjTxtPassword(JPasswordField jTxtPassword) {
        this.jTxtPassword = jTxtPassword;
    }

    public JTextField getjTxtUsername() {
        return jTxtUsername;
    }

    public void setjTxtUsername(JTextField jTxtUsername) {
        this.jTxtUsername = jTxtUsername;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField jTxtPassword;
    private javax.swing.JTextField jTxtUsername;
    // End of variables declaration//GEN-END:variables
}
