/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.ProductBUS;
import BUS.TagBUS;
import DTO.ProductDTO;
import DTO.TagDTO;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ProductForm extends javax.swing.JFrame {

    DefaultTableModel tbModelProduct, tbModelTag;
    ProductBUS productBUS = new ProductBUS();
    TagBUS tagBUS = new TagBUS();
    int rowProduct = -2, rowTag = -2;
    String productId = "", productName = "";
    ArrayList<ProductDTO> products;
    ArrayList<TagDTO> tags;

    /**
     * Creates new form ProductForm
     */
    public ProductForm() {
        initComponents();
        this.setVisible(false);
        jTableProduct.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void clear() {
        tbModelTag.setRowCount(0);
        jBtnXoa.setEnabled(false);
        jBtnSua.setEnabled(false);
        jBtnThem.setEnabled(true);
        jBtnHuy.setEnabled(true);
        rowProduct = -2;
        rowTag = -2;
        productId = "";
        productName = "";
        jTextPName.setText("");
        jTextPDetail.setText("");
        jTableProduct.clearSelection();
        jTableTag.clearSelection();
    }

    public void setVisibleComponents(boolean check) {
        jLabel4.setVisible(check);
        jLabel8.setVisible(check);
        jLabel9.setVisible(check);
        jTextPName.setVisible(check);
        jScrollPane3.setVisible(check);
        jBtnThem.setVisible(check);
        jBtnSua.setVisible(check);
        jBtnHuy.setVisible(check);
        jLabel3.setVisible(!check);
        jBtnChucNang.setVisible(!check);
        jScrollPane2.setVisible(!check);
    }

    public void tableModelProduct(DefaultTableModel model) {
        Vector row;
        for (ProductDTO product : products) {
            row = new Vector();
            row.add(product.getProductId());
            row.add(product.getProductName());
            row.add(product.getProductQuantity());
            row.add(product.getProductDetail());
            model.addRow(row);
        }
    }

    public void initTableProduct(int role) {
        clear();
        setVisibleComponents(false);
        if (role != 1) {
            jBtnChucNang.setVisible(false);
            jBtnXoa.setVisible(false);
        }
        products = productBUS.getList();
        tags = tagBUS.getList();
        tbModelProduct.setRowCount(0);
        tableModelProduct(tbModelProduct);
        jTableProduct.setRowSorter(null);
        jTableProduct.setAutoCreateRowSorter(true);
        jTableProduct.setModel(tbModelProduct);
    }

    public void tableModelTag(DefaultTableModel model) {
        Vector row;
        for (TagDTO tag : tags) {
            if (tag.getProductId().equals(productId)) {
                row = new Vector();
                row.add(tag.getTagId());
                row.add(tag.getTagDateIn());
                row.add(tag.getTagGateIn());
                row.add(tag.getTagDateOut());
                row.add(tag.getTagGateOut());
                row.add(tag.getOrderId());
                model.addRow(row);
            }
        }
    }

    public void initTableTag() {
        tbModelTag.setRowCount(0);
        tableModelTag(tbModelTag);
        jTableTag.setModel(tbModelTag);
    }

    public String validation() {
        String validate = "";
        if (jTextPName.getText().equals("") || jTextPDetail.getText().equals("")) {
            validate += "Các trường thông tin không được bỏ trống!\n";
        }
        return validate;
    }

    public void themVector(DefaultTableModel model, ProductDTO productDTO) {
        Vector newrow = new Vector();
        newrow.add(productDTO.getProductId());
        newrow.add(productDTO.getProductName());
        newrow.add(productDTO.getProductQuantity());
        newrow.add(productDTO.getProductDetail());
        model.addRow(newrow);
    }

    public void suaVector(DefaultTableModel model, int row, ProductDTO productDTO) {
        model.setValueAt(productDTO.getProductName(), row, 1);
        model.setValueAt(productDTO.getProductDetail(), row, 3);
    }

    public void xoaVector(DefaultTableModel model, int row) {
        model.removeRow(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextPName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPDetail = new javax.swing.JTextArea();
        jBtnThem = new javax.swing.JButton();
        jBtnSua = new javax.swing.JButton();
        jBtnHuy = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTag = new javax.swing.JTable();
        jBtnXoa = new javax.swing.JButton();
        jBtnChucNang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Product name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 90, 30));
        jPanel1.add(jTextPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 210, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Product detail");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 90, 30));

        jTextPDetail.setColumns(20);
        jTextPDetail.setRows(5);
        jScrollPane3.setViewportView(jTextPDetail);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 210, 100));

        jBtnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnThem.setText("THÊM");
        jBtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThemActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 80, -1));

        jBtnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnSua.setText("SỬA");
        jBtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 80, -1));

        jBtnHuy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnHuy.setText("HỦY");
        jBtnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHuyActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("THÔNG TIN SẢN PHẨM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 163, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SẢN PHẨM");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 13, 243, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DANH SÁCH SẢN PHẨM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 163, 40));

        Vector tableCol = new Vector();
        tableCol.add("Product ID");
        tableCol.add("Product Name");
        tableCol.add("Remaining");
        tableCol.add("Product Detail");

        tbModelProduct = new DefaultTableModel (tableCol,0){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        jTableProduct.setModel (tbModelProduct);
        jTableProduct.setShowGrid(true);
        jTableProduct.setFocusable(false);
        jTableProduct.setIntercellSpacing(new Dimension(0,0));
        jTableProduct.setRowHeight(25);
        jTableProduct.getTableHeader().setOpaque(false);
        jTableProduct.setFillsViewportHeight(true);
        //        jTableProduct.getTableHeader().setBackground(new Color(145,209,242));
        //        jTableProduct.getTableHeader().setForeground(new Color(51, 51, 51));
        jTableProduct.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        //        jTableProduct.setSelectionBackground(new Color(76,121,255));
        jTableProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableProduct.setGridColor(new java.awt.Color(83, 86, 88));
        jTableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductMouseClicked(evt);
            }
        });
        jTableProduct.getColumn (tableCol.elementAt (0)).setPreferredWidth (100);
        jTableProduct.getColumn (tableCol.elementAt (1)).setPreferredWidth (150);
        jTableProduct.getColumn (tableCol.elementAt (2)).setPreferredWidth (100);
        jTableProduct.getColumn (tableCol.elementAt (3)).setPreferredWidth (250);
        jTableProduct.setAutoResizeMode (javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTableProduct);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 380, 290));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("CHI TIẾT TAG");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 163, 40));

        Vector tableColDetail = new Vector();
        tableColDetail.add("Tag ID");
        tableColDetail.add("Date In");
        tableColDetail.add("Gate In");
        tableColDetail.add("Date Out");
        tableColDetail.add("Gate Out");
        tableColDetail.add("Order ID");

        tbModelTag = new DefaultTableModel (tableColDetail,0){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        jTableTag.setModel (tbModelTag);
        jTableTag.setShowGrid(true);
        jTableTag.setFocusable(false);
        jTableTag.setIntercellSpacing(new Dimension(0,0));
        jTableTag.setRowHeight(25);
        jTableTag.getTableHeader().setOpaque(false);
        jTableTag.setFillsViewportHeight(true);
        //        jTableProduct.getTableHeader().setBackground(new Color(145,209,242));
        //        jTableProduct.getTableHeader().setForeground(new Color(51, 51, 51));
        jTableTag.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        //        jTableProduct.setSelectionBackground(new Color(76,121,255));
        jTableTag.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableTag.setGridColor(new java.awt.Color(83, 86, 88));
        jTableTag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTagMouseClicked(evt);
            }
        });
        jTableTag.getColumn (tableColDetail.elementAt (0)).setPreferredWidth (230);
        jTableTag.getColumn (tableColDetail.elementAt (1)).setPreferredWidth (150);
        jTableTag.getColumn (tableColDetail.elementAt (2)).setPreferredWidth (100);
        jTableTag.getColumn (tableColDetail.elementAt (3)).setPreferredWidth (150);
        jTableTag.getColumn (tableColDetail.elementAt (4)).setPreferredWidth (100);
        jTableTag.getColumn (tableColDetail.elementAt (5)).setPreferredWidth (100);
        jTableTag.setAutoResizeMode (javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTableTag);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 380, 290));

        jBtnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnXoa.setText("XÓA");
        jBtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 80, -1));

        jBtnChucNang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnChucNang.setText(".  .  .");
        jBtnChucNang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChucNangActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnChucNang, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, 799, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, 483, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductMouseClicked
        // TODO add your handling code here:
        int row = jTableProduct.getSelectedRow();
//        System.out.println("row: " + row);
        if (row == rowProduct) {
            jTableProduct.clearSelection();
            jBtnXoa.setEnabled(false);
            jBtnSua.setEnabled(false);
            jBtnThem.setEnabled(true);
            jBtnHuy.setEnabled(true);
            rowProduct = -2;
            productId = "";
            productName = "";
            jTextPName.setText("");
            jTextPDetail.setText("");
            tbModelTag.setRowCount(0);
            return;
        }
        if (row != -1) {
            rowProduct = row;
            productId = (String) jTableProduct.getValueAt(row, 0);
            productName = (String) jTableProduct.getValueAt(row, 1);
            jTextPName.setText(productName);
            jTextPDetail.setText((String) jTableProduct.getValueAt(row, 3));
            jBtnSua.setEnabled(true);
            jBtnThem.setEnabled(false);
            jBtnHuy.setEnabled(true);
            initTableTag();
            if (tbModelTag.getRowCount() == 0) {
                jBtnXoa.setEnabled(true);
            } else {
                jBtnXoa.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jTableProductMouseClicked

    private void jTableTagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTagMouseClicked
        // TODO add your handling code here:
        int row = jTableTag.getSelectedRow();
        if (row == rowTag) {
            jTableTag.clearSelection();
            rowTag = -2;
            return;
        }
        if (row != -1) {
            rowTag = row;
        }
    }//GEN-LAST:event_jTableTagMouseClicked

    private void jBtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnXoaActionPerformed
        // TODO add your handling code here:
        if (productId != null || !productId.equals("")) {
//            System.out.println("row count: " + tbModelTag.getRowCount());
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa sản phẩm?",
                    "Xác nhận", JOptionPane.OK_CANCEL_OPTION);
            if (confirm == JOptionPane.OK_OPTION) {
                if (productBUS.deleteProduct(productId)) {
                    xoaVector(tbModelProduct, rowProduct);
                    JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công!");
                    clear();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công!");
                }
            }
        }
    }//GEN-LAST:event_jBtnXoaActionPerformed

    private void jBtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnThemActionPerformed
        // TODO add your handling code here:
        String check = validation();
        if (check.equals("")) { //validation
            for (ProductDTO a : products) {
                if (a.getProductName().equals(jTextPName.getText())) {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại! Tên sản phẩm đã tồn tại!");
                    return;
                }
            }
            ProductDTO productDTO = new ProductDTO("", (String) jTextPName.getText(), 0, (String) jTextPDetail.getText());
            if (productBUS.insertProduct(productDTO)) {
                themVector(tbModelProduct, productDTO);
                products.add(productDTO);
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại!");
            }
        } else {
            JOptionPane.showMessageDialog(this, check);
        }
    }//GEN-LAST:event_jBtnThemActionPerformed

    private void jBtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSuaActionPerformed
        // TODO add your handling code here:
        String check = validation();
        if (check.equals("")) { //validation
            for (ProductDTO a : products) {
                if (a.getProductName().equals(jTextPName.getText()) && !a.getProductName().equals(productName)) {
                    JOptionPane.showMessageDialog(this, "Sửa sản phẩm thất bại! Tên sản phẩm đã tồn tại!");
                    return;
                }
            }
            ProductDTO productDTO = new ProductDTO((String) tbModelProduct.getValueAt(rowProduct, 0), (String) jTextPName.getText(), 0, (String) jTextPDetail.getText());
            if (productBUS.updateProduct(productDTO)) {
                suaVector(tbModelProduct, rowProduct, productDTO);
                products.set(rowProduct, productDTO);
                JOptionPane.showMessageDialog(this, "Sửa sản phẩm thành công!");
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa sản phẩm thất bại!");
            }
        } else {
            JOptionPane.showMessageDialog(this, check);
        }
    }//GEN-LAST:event_jBtnSuaActionPerformed

    private void jBtnChucNangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChucNangActionPerformed
        // TODO add your handling code here:
        setVisibleComponents(true);
    }//GEN-LAST:event_jBtnChucNangActionPerformed

    private void jBtnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHuyActionPerformed
        // TODO add your handling code here:
        setVisibleComponents(false);
    }//GEN-LAST:event_jBtnHuyActionPerformed

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnChucNang;
    private javax.swing.JButton jBtnHuy;
    private javax.swing.JButton jBtnSua;
    private javax.swing.JButton jBtnThem;
    private javax.swing.JButton jBtnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JTable jTableTag;
    private javax.swing.JTextArea jTextPDetail;
    private javax.swing.JTextField jTextPName;
    // End of variables declaration//GEN-END:variables
}
